#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

remark_run() {
    node -r ts-node/register/transpile-only node_modules/remark-cli/cli.js readme.md "$@"
}

remark_output() {
    remark_run --output
}

build() {
    ng-packagr
}

eslint_run() {
    eslint src --ext ts
}

lint_watch() {
    npm run tsclint:w 2>&1 &
    npm run eslint:w 2>&1 &
}

"$@"
